"""
Compiles the full StockPilot AI agentic graph.

Architecture: (Figure generated by ClaudeAI)
                         ┌──────────────────────┐
    user query ──────────► classify_query       │  (Supervisor)
                         │  - extract ticker    │
                         │  - classify route    │
                         └─────────┬────────────┘
                                   │
              ┌────────────────────┼───────────────────────┐
              ▼                    ▼                       ▼
    ┌──────────────────┐  ┌─────────────────────┐  ┌───────────────┐
    │  News RAG        │  │  Stock Data RAG     │  │  General      │
    │  retrieve_news   │  │  generate_sql       │  │  (direct LLM) │
    │  grade_docs      │  │  execute_sql        │  └───────┬───────┘
    │  [web_search]    │  │  generate_stock_    │          │
    │  generate_answer │  │    answer           │          │
    └────────┬─────────┘  └─────────┬───────────┘          │
             └──────────────────────┴──────────────────────┘
                                    │
                              final_answer
                                    │
                                   END

Usage:
from agents.graph import get_graph

graph = get_graph()
result = graph.invoke({"query": "What's the latest news on NVDA?"})
print(result["final_answer"])
"""

import logging
from functools import lru_cache

from langgraph.graph import END, StateGraph

from agents.state import AgentState, initial_state
from agents.supervisor import classify_query, general_answer, route_query
from agents.news_rag import build_news_rag_graph
from agents.stock_data_rag import build_stock_data_rag_graph

logger = logging.getLogger(__name__)


def build_graph():
    """
    Build and compile the full multi-agent graph.

    The supervisor acts as the top-level node. Each subgraph is compiled
    separately and added as a node in the parent graph, which is the
    standard LangGraph pattern for multi-agent supervisor architectures.
    """
    # Build subgraphs
    news_rag_graph       = build_news_rag_graph()
    stock_data_rag_graph = build_stock_data_rag_graph()

    # Parent graph
    graph = StateGraph(AgentState)

    # Add supervisor node
    graph.add_node("classify_query", classify_query)

    # Add subgraph nodes (each is a compiled graph acting as a single node)
    graph.add_node("news_rag_subgraph", news_rag_graph)
    graph.add_node("stock_data_rag_subgraph", stock_data_rag_graph)
    graph.add_node("general_answer", general_answer)

    # Entry point
    graph.set_entry_point("classify_query")

    # Conditional routing from supervisor
    graph.add_conditional_edges(
        "classify_query",
        route_query,
        {
            "news_rag_subgraph": "news_rag_subgraph",
            "stock_data_rag_subgraph": "stock_data_rag_subgraph",
            "general_answer": "general_answer",
        },
    )

    # All paths converge to END
    graph.add_edge("news_rag_subgraph", END)
    graph.add_edge("stock_data_rag_subgraph", END)
    graph.add_edge("general_answer", END)

    compiled = graph.compile()
    logger.info("StockPilot AI graph compiled successfully")
    return compiled


@lru_cache(maxsize=1)
def get_graph():
    """
    Return the cached compiled graph (singleton).
    Uses lru_cache so the graph is only built once per process.
    """
    return build_graph()


def run_query(query: str) -> dict:
    """
    Convenience function: run a query through the full graph.

    Parameters:
    query : str — natural language question

    Returns:
    dict with keys: final_answer, route, ticker, messages, error
    """
    graph  = get_graph()
    state  = initial_state(query)
    result = graph.invoke(state)

    logger.info(
        f"Query complete | route={result.get('route')} | "
        f"ticker={result.get('ticker')} | "
        f"answer_len={len(result.get('final_answer') or '')}"
    )
    return result